---
- hosts: all
  user: root
  tasks:
    - name: Clear cache on centos
      ansible.builtin.dnf:
        update_cache: yes
      when: ansible_distribution == "CentOS"

    - name: add httpd on centos
      dnf:
        name: httpd
        state: latest
      when: ansible_distribution == "CentOS"
