---

- hosts: all
  become: true
  tasks:
    - name: install apache2 package
      apt:
        name: 
          - "{{ php_package }}"
          - "{{ apache_package }}"
        state: latest
        update_cache: true
      when: ansible_distribution == "Ubuntu"

    - name: install httpd package
      dnf:
        name:
          - "{{ php_package }}"
          - "{{ apache_package }}"
        state: latest
        update_cache: true
      when: ansible_distribution == "CentOS"


