---
- hosts: ubuntu
  become: true
  tasks:
    - name: clean cache
      apt: 
        update_cache: true
    - name: uninstall apache2 & php packages
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: absent
      when: ansible_distribution == "Ubuntu"

